## config context path to "/" by setting an empty string
server:
  port: 8080
  error:
    whitelabel:
      enabled: false            # disable default error-page

spring:
  pid:
    file: agenspop.pid          # pid filename when start process (not working)
  main:
    banner-mode: "off"          # hide spring banner when start process
  resources:
    cache:
      period: 3600              # seconds

agens:
  api:
    base-path: /api
    query-timeout: 600000       # 1000 ms = 1 sec
  elasticsearch:
#    host: 27.117.163.21
#    port: 15619
    host: 192.168.0.54
    port: 8087
    username:
    password:
    scroll-limit: -1            # -1(unlimit) or more than 2500
    vertex-index: elasticvertex
    edge-index: elasticedge
    edge-validation: false      # if true, check valid edge on each request (make slow)
    index-shards: 2             # when create index, apply to setting
    index-replicas: 0           # when create index, apply to setting
  product:
    name: agenspop-es
    version: 0.7.3-dev
    hello-msg: agenspop-elasticgraph v1.0 (since 2019-08-01)
  front:
    debug: false                # display elapsedTimes of Visualization(Workspace) about loading, rendering
